/* autogenerated by Processing revision 1306 on 2025-11-06 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class ProyekGabungan extends PApplet {



int state = 0;

SceneLoading sceneLoading;
SceneMenu sceneMenu;
SceneKota sceneKota;
ScenePegunungan scenePegunungan;
ScenePantai scenePantai;

public void setup() {
  /* size commented out by preprocessor */; 
  
  sceneLoading = new SceneLoading();
  sceneMenu = new SceneMenu();
  
  sceneKota = new SceneKota(this);
  scenePegunungan = new ScenePegunungan(this);
  scenePantai = new ScenePantai(this);
}

public void draw() {
  switch(state) {
    case 0:
      sceneLoading.tampilkan();
      break;
    case 1:
      sceneMenu.tampilkan();
      break;
    case 2:
      sceneKota.tampilkan();
      break;
    case 3:
      scenePegunungan.tampilkan();
      break;
    case 4:
      scenePantai.tampilkan();
      break;
  }
}

public void keyPressed() {
  if (key == 'm' || key == 'M') {
    if (state == 2 || state == 3 || state == 4) {
      sceneKota.stopMusic();
      scenePegunungan.stopMusic();
      scenePantai.stopMusic();
      
      state = 1; 
    }
  }
}

public void mousePressed() {
  if (state == 1) {
    sceneMenu.handleMouseClick();
  }
}

public void goToScene(int newState) {
  state = newState;
  
  sceneKota.stopMusic();
  scenePegunungan.stopMusic();
  scenePantai.stopMusic();
  if (state == 2) sceneKota.playMusic();
  if (state == 3) scenePegunungan.playMusic();
  if (state == 4) scenePantai.playMusic();
}
class SceneKota {

  SoundFile audioStreet;
  Langit langit;
  Jalan jalan;
  Gedung gedung1, gedung2, gedung3, gedung4;
  Kursi kursi1, kursi2;
  Pohon pohon1, pohon2;
  mobil mobil;

  SceneKota(PApplet app) {
    audioStreet = new SoundFile(app, "data/street.mp3"); 
    
    langit = new Langit();
    jalan = new Jalan();
    gedung1 = new Gedung(100, 500, 190, 400, color(60, 50, 70));
    gedung2 = new Gedung(250, 500, 100, 300, color(45, 40, 60)); 
    gedung3 = new Gedung(400, 500, 100, 350, color(70, 60, 80));
    gedung4 = new Gedung(550, 500, 190, 450, color(55, 45, 65)); 
    
    kursi1 = new Kursi(340, 520, color(70, 50, 40));
    kursi2 = new Kursi(480, 520, color(70, 50, 40)); 
    
    pohon1 = new Pohon(690, 500);
    pohon2 = new Pohon(250, 500);
    mobil = new mobil();
  }

  public void tampilkan() {
    
    pushMatrix();
    translate(0, 10, 0);
    langit.tampilkan();
    popMatrix();
    
    pushMatrix();
    translate(0, 0, 20);
    jalan.tampilkan();
    gedung1.tampilkan();
    gedung2.tampilkan();
    gedung3.tampilkan();
    gedung4.tampilkan();
    kursi1.tampilkan();
    kursi2.tampilkan();
    pohon1.tampilkan();
    pohon2.tampilkan();
    
    popMatrix();
    
    
    pushMatrix();
    translate(100, 420, 100);
    scale(0.2f); 
    
    stroke(1);
    strokeWeight(2);
    
    mobil.gambarMobil(100, 400);
    
    popMatrix();
    
    
    pushMatrix();
    translate(0, 0, 40);
    displayHint();
    popMatrix();
  }

  public void playMusic() {
    audioStreet.loop();
  }

  public void stopMusic() {
    audioStreet.stop();
  }
  
  public void displayHint() {
    noStroke();
    fill(255, 255, 255, 180);
    rect(40, 25, 200, 30, 5);
    fill(0);
    textAlign(LEFT, CENTER);
    textSize(14);
    text("Tekan M untuk ke Menu", 50, 40);
  }

  class Langit { 
    Langit() {}
    public void tampilkan() {  
      for (int i = 0; i < 300; i++) {
        float inter = map(i, 0, 300, 0, 1);
        int c = lerpColor(color(25, 25, 70), color(255, 140, 80), inter);
        stroke(c);
        line(0, i, width, i);
      } 
      for (int i = 300; i < 500; i++) {
        float inter = map(i, 300, 500, 0, 1);
        int c = lerpColor(color(255, 140, 80), color(255, 100, 130), inter);
        stroke(c);
        line(0, i, width, i);
      }
      noStroke();
      
      pushMatrix();
      translate(0, 0, 10);
      fill(255, 120, 80, 200);
      ellipse(100, 100, 180, 180);
      fill(255, 140, 100, 100);
      ellipse(100, 100, 240, 240); 
      popMatrix();
    }
  }

  class Jalan { 
    float offset = 0;
    Jalan() {}
    public void tampilkan() {
      fill(80, 75, 70);
      rect(0, 500, width, 100); 
      fill(40, 38, 35);
      rect(0, 550, width, 50);
      stroke(200, 180, 120);
      strokeWeight(1); 
      for (int i = 0; i < width; i += 40) {
        line(i + offset, 575, i + 20 + offset, 575);
      }
      noStroke();
      
      offset -= 2;
      if (offset <= -40) {
        offset = 0;
      }
    }
  }

  class Gedung { 
    float x, y, w, h;
    int c;
    
    Gedung(float x, float y, float w, float h, int c) { 
      this.x = x;
      this.y = y; this.w = w; this.h = h; this.c = c;
    }
    
    public void generateWindow() {
      for (float i = x + 10; i < x + w - 10; i += 30) {
        for (float j = y - h + 10; j < y - 10; j += 30) {
          fill(255, 200, 150);
          rect(i, j, 20, 20);
        }
      }
    }
    
    public void tampilkan() {
      fill(c);
      rect(x, y - h, w, h);
      generateWindow();
    }
  }
  
  class Kursi { 
    float x, y;
    int c;
    
    Kursi(float x, float y, int c) {
      this.x = x;
      this.y = y; this.c = c; 
    }
    
    public void tampilkan() {
      fill(c);
      rect(x, y, 50, 8);
      rect(x, y + 8, 50, 15);
      rect(x, y + 8, 5, 22);
      rect(x + 45, y + 8, 5, 22);
    }
  }
  
  class Pohon { 
    float x, y;
    Pohon(float x, float y) {
      this.x = x;
      this.y = y; 
    }
    
    public void tampilkan() {
      fill(80, 50, 30);
      rect(x, y, 20, 50);
      fill(50, 80, 45);
      ellipse(x + 10, y - 35, 80, 80); 
    }
  }
}
class SceneLoading {
  
  int loading = 0;
  float perputaranX = 0;
  float perputaranY = 0;
  String text = "MEMUAT...";

  SceneLoading() {
  }

  public void tampilkan() {
    background(100, 150, 200);
    
    kotak();
    loadingBar();
  }

  public void kotak() {
    pushMatrix();
    
    translate(width/2, height/2-130, 10);
    rotateY(perputaranX);
    rotateZ(perputaranY);
    
    fill(50, 80, 120);
    box(160);
    
    perputaranY += 0.05f;
    perputaranX += 0.05f;
    
    popMatrix();
    noFill();
  }

  public void loadingBar() { 
    pushMatrix();
    translate(0, 0, 10);
    
    rect(width/2-200, height/2+50, 410, 40);
    loadingFill();
    pushMatrix();
    translate(0, 0, 30);
    textSize(20);
    fill(0);
    text(text, width/2-35, height/2+73);
    popMatrix();
    
    popMatrix();
  }

  public void loadingFill() {
    pushMatrix();
    translate(10, 2, 20); 
    noStroke();
    fill(50, 80, 120);
    
    rect(width/2-200, height/2+50, loading, 30);
    if (loading < 388) {
      loading += 2;
    } else {
      state = 1; 
    }
    
    popMatrix();
    noFill();
    stroke(1);
  }
}
class SceneMenu {

  float btnKotaX = 300, btnKotaY = 200, btnW = 200, btnH = 50;
  float btnGunungX = 300, btnGunungY = 300, btnHutanX = 300, btnHutanY = 400;

  SceneMenu() {
  }

  public void tampilkan() {
    background(50, 50, 80);
    
    textSize(40);
    fill(255);
    textAlign(CENTER, CENTER);
    text("PILIH PANORAMA", width/2, 100);

    fill(100, 100, 150);
    
    if (isMouseOver(btnKotaX, btnKotaY, btnW, btnH)) {
      fill(150, 150, 200);
    }
    rect(btnKotaX, btnKotaY, btnW, btnH, 10);
    
    fill(255);
    textSize(25);
    text("KOTA", btnKotaX + btnW/2, btnKotaY + btnH/2);

    fill(100, 150, 100);
    if (isMouseOver(btnGunungX, btnGunungY, btnW, btnH)) {
      fill(150, 200, 150);
    }
    rect(btnGunungX, btnGunungY, btnW, btnH, 10);
    fill(255);
    textSize(25);
    text("PEGUNUNGAN", btnGunungX + btnW/2, btnGunungY + btnH/2);
    
    fill(150, 150, 100);
    if (isMouseOver(btnHutanX, btnHutanY, btnW, btnH)) {
      fill(200, 200, 150);
    }
    rect(btnHutanX, btnHutanY, btnW, btnH, 10);
    fill(255);
    textSize(25);
    text("PANTAI", btnHutanX + btnW/2, btnHutanY + btnH/2);
  }

  public void handleMouseClick() {
    
    if (isMouseOver(btnKotaX, btnKotaY, btnW, btnH)) {
      goToScene(2);
    }
    
    if (isMouseOver(btnGunungX, btnGunungY, btnW, btnH)) {
      goToScene(3);
    }
    
    if (isMouseOver(btnHutanX, btnHutanY, btnW, btnH)) {
      goToScene(4);
    }
  }

  public boolean isMouseOver(float x, float y, float w, float h) {
    return (mouseX >= x && mouseX <= x + w &&
            mouseY >= y && mouseY <= y + h);
  }
}
class ScenePantai {

  SoundFile musik;
  float waveOffset = 0.0f;
  float offsetX = 0;
  float speed = 3;
  mobil mobil;

  ScenePantai(PApplet app) {
    musik = new SoundFile(app, "./data/pantai.mp3"); 
    mobil = new mobil();
  }

  public void tampilkan() {
    
    background(135, 206, 235);
    
    noStroke();
    fill(255, 255, 0);
    ellipse(700, 100, 80, 80);

    fill(0, 119, 190);
    noStroke();
    
    beginShape();
    float xoff = waveOffset;
    
    for (float x = 0; x <= width; x += 10) {
      float y = map(noise(xoff), 0, 1, 280, 300);
      vertex(x, y);
      xoff += 0.05f;
    }
    vertex(width, 500);
    vertex(0, 500);    
    endShape(CLOSE);
    
    waveOffset += 0.01f;
    fill(245, 222, 179);
    noStroke();
    beginShape();
    vertex(0, 350);
    curveVertex(0, 350);
    curveVertex(250, 420);
    curveVertex(500, 390);
    curveVertex(800, 450);
    vertex(800, 450);
    vertex(800, 500);
    vertex(0, 500);
    endShape(CLOSE);

    fill(139, 69, 19);
    noStroke();
    quad(280, 415, 270, 390, 400, 390, 390, 415);
    stroke(139, 69, 19);
    strokeWeight(4);
    line(350, 400, 350, 330);
    noStroke();
    fill(0xFFFF0000);
    rect(349, 320, 50, 20);
    fill(0xFFFFFAFA);
    rect(349, 340, 50, 20);
    
    
    fill(255, 0, 0);
    noStroke();
    quad(540, 450, 620, 450, 600, 410, 560, 410);
    stroke(100);
    strokeWeight(4);
    line(540, 440, 540, 380);
    
    fill(0xFFCCFA03);
    noStroke();
    arc(540, 380, 100, 100, PI, TWO_PI);
    fill(139, 69, 19);
    noStroke();
    rect(100, 280, 20, 220);
    rect(180, 300, 20, 200);
    
    stroke(34, 139, 34);
    strokeWeight(7);
    noFill();
    
    bezier(110, 280, 90, 260, 70, 250, 50, 260);
    bezier(110, 280, 130, 260, 150, 250, 170, 260); 
    bezier(110, 280, 70, 280, 40, 290, 20, 310);
    bezier(110, 280, 150, 280, 180, 290, 200, 310); 
    bezier(110, 280, 90, 300, 80, 320, 70, 340);
    bezier(110, 280, 130, 300, 140, 320, 150, 340); 
    
    bezier(190, 300, 170, 280, 150, 270, 130, 280);
    bezier(190, 300, 210, 280, 230, 270, 250, 280); 
    bezier(190, 300, 150, 300, 120, 310, 100, 330);
    bezier(190, 300, 230, 300, 260, 310, 280, 330); 
    bezier(190, 300, 170, 320, 160, 340, 150, 360);
    bezier(190, 300, 210, 320, 220, 340, 230, 360); 
    bezier(190, 300, 230, 320, 250, 340, 260, 360);
    noStroke();
    fill(101, 67, 33);
    ellipse(105, 295, 20, 20); 
    ellipse(120, 295, 20, 20);
    ellipse(185, 315, 20, 20);
    ellipse(200, 315, 20, 20); 

    fill(0xFF2E2E2E);
    rect(0, 500, 800, 100);
    fill(0xFFABADAB);
    rect(0, 450, 800, 10);

    fill(0xFFCBBB23);
    float offsetGaris = offsetX % 60;
    for (int x = -60; x < 800; x += 60) {
      rect(x + offsetGaris, 545, 30, 10);
    }
    
    fill(0xFFABADAB);
    float offsetTiang = offsetX % 40;
    for (int x = -40; x < 800; x += 40) {
      rect(x + offsetTiang, 450, 10, 50);
    }

    offsetX -= speed;
    stroke(1);
    strokeWeight(2);
    mobil.gambarMobil(20, 450);
    noStroke();
    
    displayHint();
  }

  public void playMusic() {
    musik.loop();
  }

  public void stopMusic() {
    musik.stop();
  }
  
  public void displayHint() {
    noStroke();
    fill(255, 255, 255, 180);
    rect(20, 20, 200, 30, 5);
    fill(0);
    textAlign(LEFT, CENTER);
    textSize(14);
    text("Tekan M untuk ke Menu", 35, 35);
  }
}
class ScenePegunungan {

  SoundFile suaraBGM;
  mobil mobil;

  int bergerak = 800;
  int bergerak2 = 800;
  boolean ulang = false;
  float kecepatan = 2;

  //animasi jalanan dan pagar
  boolean animasi= true;//memakai animasi atau tidak
  boolean animasiMobil = false; //animasi mobil
  int bergerakJalanan = 0;//jarak muncul
  int bergerakJalanan2 = 800;//jarak muncul
  boolean ulangJalanan = false; //triger animasi jalanan ke 2 dimulai
  float kecepatanJalanan = 5; //kecepatan animasi

  //animasi mobil
  float KecepatanTerbang = 5;
  float kecepatanPutar = 5;
  boolean terbang = true;
  boolean putar = true;
  float perputaran = 0;
  int terbangTiap = 0;
  int coba = 0;
  float tinggiTerbang =0;//tinggi terbang saat ini

  ScenePegunungan(PApplet app) {
    mobil = new mobil();
    suaraBGM = new SoundFile(app, "./data/suaraAngin.mp3");
  }

  public void tampilkan() {
    background(0xFF3399FF);

    parkiran();
    dataranHijau();
    gunung(-87.5f, -43.75f);
    gunung(135, 0);
    gunung(385, -15);
    gunung(610, 60);
    munculPagar(0, 390, animasi);
    tambalanHijau();
    matahari(355, 20);
    animasiAwan();
    jalan(0, 490, animasi);
    animasiMobil(10, 430, animasiMobil);

    noStroke();

    displayHint();
  }

  public void playMusic() {
    suaraBGM.loop();
  }

  public void stopMusic() {
    suaraBGM.stop();
  }

  public void displayHint() {
    noStroke();
    fill(255, 255, 255, 180);
    rect(20, 20, 200, 30, 5);
    fill(0);
    textAlign(LEFT, CENTER);
    textSize(14);
    text("Tekan M untuk ke Menu", 35, 35);
  }

  public void parkiran() {
    pushMatrix();
    fill(0xFF808080);
    translate(0, 430);
    rect(0, 0, 800, 170);
    fill(255);
    popMatrix();
  }

  public void pagarPanjang(float x, float y) {
    fill(0xFFCC6600);
    while (x < 800) {
      pagar(x, y);
      x+=100;
    }
    fill(255);
  }

  public void pagar(float x, float y) {
    pushMatrix();
    //translate(0, 0);
    rect(x+90, y, 10, 50);//paku

    rect(x, y, 100, 5);//pembatas atas
    rect(x, y+15, 100, 5);//pembatas tengah
    rect(x, y+30, 100, 5);//pembatas bawah
    popMatrix();
  }

  public void animasiPagar(float x, float y) {
    if (ulangJalanan) {
      pushMatrix();
      translate(bergerakJalanan2, 0);

      pagarPanjang(x, y);//bagian utama

      popMatrix();
      bergerakJalanan2-=kecepatanJalanan;
    }
    if (bergerakJalanan == 0) {
      ulangJalanan = true;
    }

    if (bergerakJalanan2 <= -800) {
      bergerakJalanan2 = 800;
    }

    if (bergerakJalanan <= -800) {
      bergerakJalanan = 800;
    }
    pushMatrix();
    translate(bergerakJalanan, 0);

    pagarPanjang(x, y);//bagian utama

    popMatrix();
    bergerakJalanan-=kecepatanJalanan;
  }

  public void munculPagar(float x, float y, boolean animation) {
    if (animation) {
      animasiPagar(x, y);
    } else {
      pagarPanjang(x, y);
    }
  }

  public void gunung(float x, float y) {
    //tinggi = 315  dan panjang = 420

    x-=52.5f;
    y+=52.5f;

    //kordinat umum
    int x2 = 210;
    int y2 = 315;

    pushMatrix();
    translate(x, y);
    fill(0xFF37A037);
    beginShape();
    vertex(-x2+x2, y2);
    vertex(0+x2, 0);
    vertex(x2+x2, y2);
    endShape();
    fill(255);
    popMatrix();
  }

  public void dataranHijau() {
    pushMatrix();
    translate(0, 0);
    fill(0xFF37A037);
    rect(0, 270, 800, 160);
    fill(255);
    popMatrix();
  }

  public void tambalanHijau() {
    pushMatrix();
    noStroke();
    translate(0, 0);
    fill(0xFF37A037);
    rect(490, 345, 40, 30);
    fill(255);
    stroke(0);
    popMatrix();
  }

  public void matahari(float x, float y) {
    pushMatrix();
    translate(x, y);
    noStroke();
    fill(0xFFFFFF00);
    circle(0+40, 0+40, 80);
    fill(255);
    popMatrix();
  }

  public void bulat(float x, float y) {
    pushMatrix();
    x+=20;
    y+=20;
    translate(x, y);
    circle(0, 0, 40);
    popMatrix();
  }

  public void awan(float x, float y) {
    pushMatrix();

    translate(x, y);
    noStroke();
    //bulatan awan
    bulat(0, 11.5500f);
    bulat(14, 0);
    bulat(50, 0);
    bulat(69, 12.5499f);
    bulat(54, 30);
    bulat(14, 30);

    //noStroke();
    rect(14, 12.5499f, 81, 40);
    rect(34, 10.5499f, 40, 20);
    rect(34, 34.5499f, 40, 20);
    rect(11, 15.55f, 10, 10);
    stroke(0);
    popMatrix();
  }

  public void animasiAwan() {
    if (ulang) {
      pushMatrix();
      translate(bergerak2, 0);
      awan(140, 16);
      awan(450, 110);
      awan(670, 47.5f);
      popMatrix();
      bergerak2 -= kecepatan;
    }

    if (bergerak == 0) {
      ulang = true;
    }

    if (bergerak2 <= -800) {
      bergerak2 = 800;
    }

    if (bergerak <= -800) {
      bergerak = 800;
    }

    pushMatrix();
    translate(bergerak, 0);
    awan(140, 16);
    awan(450, 110);
    awan(670, 47.5f);
    popMatrix();
    bergerak -= kecepatan;
  }

  public void jalan(float x, float y, boolean animation) {
    pushMatrix();
    translate(x, y);
    noStroke();
    fill(0xFF4D4D4D);
    rect(0, 0, 800, 110);
    fill(255);
    popMatrix();

    if (animation) {
      animasiJalanan(x, y);
    } else {
      garisJalan(x, y);
    }
  }

  public void garisJalan(float x, float y) {
    y+=55;
    pushMatrix();
    translate(0, 0);
    while (x < 800) {
      rect(x, y, 40, 5);
      x+=80;
    }
    popMatrix();
  }

  public void animasiJalanan(float x, float y) {
    if (ulangJalanan) {
      pushMatrix();
      translate(bergerakJalanan2, 0);

      garisJalan(x, y);//bagian utama

      popMatrix();
      bergerakJalanan2-=kecepatanJalanan;
    }
    if (bergerakJalanan == 0) {
      ulangJalanan = true;
    }

    if (bergerakJalanan2 <= -800) {
      bergerakJalanan2 = 800;
    }

    if (bergerakJalanan <= -800) {
      bergerakJalanan = 800;
    }
    pushMatrix();
    translate(bergerakJalanan, 0);

    garisJalan(x, y);//bagian utama

    popMatrix();
    bergerakJalanan-=kecepatanJalanan;
  }

  public void animasiMobil(float x, float y, Boolean animation) {
    pushMatrix();
    translate(x, y);
    stroke(1);

    if (animation) {
      pushMatrix();
      translate(0, tinggiTerbang);

      translate(0, tinggiTerbang);
      if (tinggiTerbang <= -200 && putar && perputaran < 359) { //animasi berputar
        translate(145, 66.275f); // Pindah ke pusat mobil
        rotate(radians(perputaran));
        translate(-145, -66.275f); // Kembali ke posisi semula
        perputaran+=kecepatanPutar;
      } else if (perputaran >= 359) {// berhenti berputar
        terbang = false;
        putar = false;
        perputaran =0;
      }

      if (terbang && tinggiTerbang > -200) {
        tinggiTerbang -= KecepatanTerbang;
      } else if (!putar) {
        if (!terbang && tinggiTerbang < 0) {
          // Turun kembali ke posisi awal
          tinggiTerbang += KecepatanTerbang;
        } else if (!terbang && tinggiTerbang >= 0) {
          // Sudah kembali ke posisi awal
          tinggiTerbang = 0;
          putar = true;
          perputaran = 0;
        }
      }

      if (putar && !terbang) {
        terbangTiap += 50;
      }

      if (terbangTiap >= 800 && putar == true) {
        terbang = true;
        terbangTiap = 0; // Reset counter
      }

      stroke(1);
      mobil.gambarMobil(0, 0);
      noStroke();

      popMatrix();
      // Cek apakah sudah waktunya terbang lagi
    } else {
      pushMatrix();
      mobil.gambarMobil(0, 0);
      popMatrix();
    }
    popMatrix();
  }
}
class mobil { 
  
  public void gambarMobil(float x, float y) {
    pushMatrix();
    
    y += 50;
    translate(x, y);
    
    badanMobil();
    jendelaMobil();
    peganganPintuMobil();
    
    popMatrix();
  }

  public void badanMobil() {
    pushMatrix();
    translate(0, 0);
    fill(0xFF999900);
    rect(0, 0, 290, 60);
    
    lampuMobil();
    banMobil();
    
    popMatrix();
  }

  public void lampuMobil() {
    pushMatrix();
    translate(0, 0);
    fill(0xFFFF3333);
    rect(0, 10, 20, 10);
    fill(0xFF0000FF);
    rect(270, 10, 20, 10);
    popMatrix();
  }

  public void banMobil() {
    pushMatrix();
    translate(0, 0, 10);
    fill(0xFF4D4D4D);
    circle(53, 60, 40);
    circle(240, 62.04f, 40);

    fill(0);
    circle(53, 60, 5);
    circle(240, 62.04f, 5);
    fill(255);
    popMatrix();
  }

  public void jendelaMobil() {
    pushMatrix();
    translate(0, 0);
    fill(0xFF666666);
    
    beginShape();
    vertex(0, 0);
    vertex(45, -50);
    vertex(196, -50);
    vertex(245, 0);
    endShape();

    line(45, -50, 45, 0);
    line(100, -50, 100, 60);
    line(150, -50, 150, 60);
    line(245, 0, 245, 42);

    popMatrix();
  }

  public void peganganPintuMobil() {
    pushMatrix();
    translate(0, 0);
    fill(255);
    
    rect(110, 10, 8, 3);
    rect(160, 10, 8, 3);
    popMatrix();
  }
}


  public void settings() { size(800, 600, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "ProyekGabungan" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
